language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - echo "Tests pending"

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
